# Generated by Django 5.1.3 on 2025-09-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/resources/static/images/logo.png', upload_to='avatar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkak'), ('FEMALE', 'Ayol')], default='male', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('director', 'Director'), ('producer', 'Rejisyor'), ('actor', 'Aktyor')], default='actor', max_length=255),
        ),
    ]
