# Generated by Django 5.1.3 on 2025-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_age_user_avatar_user_gender_user_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/logo.png', upload_to='avatar/'),
        ),
    ]
