# Generated by Django 5.1.3 on 2025-09-24 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_tg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='info',
        ),
        migrations.CreateModel(
            name='ActorprofileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism familya')),
                ('age', models.IntegerField(verbose_name='Yoshi')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('FEMALE', 'Ayol')], default='male', verbose_name='Jinsi')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(default='avatar/logo.png', upload_to='avatar/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ActorprofileModel',
                'verbose_name_plural': 'ActorprofileModels',
                'db_table': 'ActorProfile',
            },
        ),
    ]
