# Generated by Django 5.1.3 on 2025-09-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_managermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actorprofilemodel',
            name='full_name',
        ),
    ]
