# Generated by Django 5.1.3 on 2025-09-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_countrymodel_studiomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('anime_type', models.CharField(choices=[('series', 'Serial'), ('movie', "To'liq metraj")], default='movie', max_length=15)),
            ],
            options={
                'verbose_name': 'AnimeModel',
                'verbose_name_plural': 'AnimeModels',
                'db_table': 'anime',
            },
        ),
    ]
