# Generated by Django 5.1.3 on 2025-09-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role_directormodel'),
        ('api', '0003_animemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'YearModel',
                'verbose_name_plural': 'YearModels',
                'db_table': 'year',
            },
        ),
        migrations.AddField(
            model_name='animemodel',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.actorprofilemodel'),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.countrymodel'),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='episodes_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.studiomodel'),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.yearmodel'),
        ),
    ]
