# Generated by Django 5.1.3 on 2025-09-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_managermodel'),
        ('api', '0004_yearmodel_animemodel_actors_animemodel_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendareventmodel',
            old_name='date',
            new_name='record_date',
        ),
        migrations.RemoveField(
            model_name='animemodel',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='calendareventmodel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='calendareventmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='calendareventmodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='calendareventmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='animemodel',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.directormodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animemodel',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.managermodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendareventmodel',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='actors', to='accounts.actorprofilemodel'),
        ),
        migrations.AddField(
            model_name='calendareventmodel',
            name='anime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.animemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendareventmodel',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.directormodel'),
            preserve_default=False,
        ),
    ]
